# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  branches:
    include:
    - master
    
pool:

  vmImage: 'ubuntu-latest'

variables:
  - group: credentials

stages:
  - stage: Test
    jobs: 
      - job: CodeBeamer
        displayName: "CodeBeamer Upload"
        steps:
          - script: |
              echo "Empty job."
    
          - task: codeBeamer@1
            inputs:
              test_xml_folder: 'Example/Test_results'
              test_run_name: '$(Build.DefinitionName) $(Build.Reason)'
              test_run_id: '$(Build.BuildId)'
              server_url: 'https://zf.codebeamer.com/'
              cb_user: '$(cb_user)'
              cb_password: '$(cb_password)'
              test_configuration_id: '2591'
              test_case_tracker_id: '29421'
              test_run_tracker_id: '29424'