# Define our host system
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

# Specify the cross compiler
SET(CMAKE_C_COMPILER $ENV{RASPBERRYPI_TOOLCHAIN_PATH}/bin/$ENV{RASPBERRYPI_TARGET_HOST}-gcc)
SET(CMAKE_CXX_COMPILER $ENV{RASPBERRYPI_TOOLCHAIN_PATH}/bin/$ENV{RASPBERRYPI_TARGET_HOST}-g++)

# Where is the target environment
SET(CMAKE_FIND_ROOT_PATH $ENV{RASPBERRYPI_TOOLCHAIN_PATH}/$ENV{RASPBERRYPI_TARGET_HOST}/sysroot/)
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --sysroot=${CMAKE_FIND_ROOT_PATH}")
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} --sysroot=${CMAKE_FIND_ROOT_PATH}")
SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} --sysroot=${CMAKE_FIND_ROOT_PATH}")

# Search for programs only in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Search for libraries and headers only in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)